rollback

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -39,34 +39,34 @@ jobs:
             -t ghcr.io/$REPO_NAME/chatbot-database:latest \
             --push .
 
-  deploy-api:
-    runs-on: ubuntu-latest
-    needs: build-and-push-api
+  # deploy-api:
+  #   runs-on: ubuntu-latest
+  #   needs: build-and-push-api
 
-    steps:
-      - name: Deploy to server
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          key: ${{ secrets.SERVER_KEY }}
-          script: |
-            set -e  # Exit on error
+  #   steps:
+  #     - name: Deploy to server
+  #       uses: appleboy/ssh-action@v0.1.6
+  #       with:
+  #         host: ${{ secrets.SERVER_HOST }}
+  #         username: ${{ secrets.SERVER_USERNAME }}
+  #         key: ${{ secrets.SERVER_KEY }}
+  #         script: |
+  #           set -e  # Exit on error
 
-            REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
+  #           REPO_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
 
-            echo "🔹 Stopping existing container (if running)..."
-            docker stop chatbot-database || true  
-            docker rm chatbot-database || true   
+  #           echo "🔹 Stopping existing container (if running)..."
+  #           docker stop chatbot-database || true  
+  #           docker rm chatbot-database || true   
 
-            echo "🔹 Pulling latest Docker image..."
-            docker pull ghcr.io/$REPO_NAME/chatbot-database:latest
+  #           echo "🔹 Pulling latest Docker image..."
+  #           docker pull ghcr.io/$REPO_NAME/chatbot-database:latest
 
-            echo "🔹 Running new container..."
-            docker run -d --name chatbot-database -p 6003:6003 \
-              -e FLASK_ENV=development \
-              -e SQLALCHEMY_DATABASE_URI="${{secrets.SQLALCHEMY_DATABASE_URI}}" \
-              ghcr.io/$REPO_NAME/chatbot-database:latest
+  #           echo "🔹 Running new container..."
+  #           docker run -d --name chatbot-database -p 6003:6003 \
+  #             -e FLASK_ENV=development \
+  #             -e SQLALCHEMY_DATABASE_URI="${{secrets.SQLALCHEMY_DATABASE_URI}}" \
+  #             ghcr.io/$REPO_NAME/chatbot-database:latest
 
-            echo "✅ Deployment complete!"
-            exit 0
+  #           echo "✅ Deployment complete!"
+  #           exit 0
